eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_HOST:http://localhost:8761/eureka}
  instance:
    hostname: "${spring.application.name}.azurewebsites.net"
    secure-port-enabled: true
    nonsecure-port-enabled: false
    nonSecurePort: 80
    securePort: 443
    instanceId: "${eureka.instance.hostname}:${spring.application.name}:443"
    statusPageUrl: "https://${eureka.hostname}:443/actuator/info"
    healthCheckUrl: "https://${eureka.hostname}:443/actuator/health"
    secureHealthCheckUrl: "https://${eureka.hostname}:443/actuator/health"

management:
  server:
    port: "${server.port}"

server:
  port: 8080

spring:
  application:
    name: uptalent-gateway
  data:
    redis:
      host: ${REDIS_HOST:}
      username: ${REDIS_USERNAME:}
      password: ${REDIS_PASSWORD:}
      port: ${REDIS_PORT:}
  cloud:
    gateway:
      default-filters:
        - name: Retry
          args:
            retries: 10
            statuses: SERVICE_UNAVAILABLE
            methods: GET,POST,PATCH,PUT,DELETE
            backoff:
              firstBackoff: 2000ms
              maxBackoff: 120000ms
              factor: 2
              basedOnPreviousValue: true
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/v1/auth/**
        - id: account-service
          uri: lb://account-service
          predicates:
            - Path=/api/v1/account/**
        - id: content-service
          uri: lb://content-service
          predicates:
            - Path=/api/v1/content/**

auth-service:
  base-url: https://auth-service/api/v1/auth
  public-key-url: ${auth-service.base-url}/public-key
