eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:8761/eureka

server:
  port: 8080

spring:
  application:
    name: api-gateway
  data:
    redis:
      host: ${REDIS_HOST:}
      username: ${REDIS_USERNAME:}
      password: ${REDIS_PASSWORD:}
      port: ${REDIS_PORT:}
  cloud:
    gateway:
      default-filters:
        - name: Retry
          args:
            retries: 5
            statuses: SERVICE_UNAVAILABLE
            methods: GET,POST,PATCH,PUT,DELETE
            backoff:
              firstBackoff: 1000ms
              maxBackoff: 60000ms
              factor: 2
              basedOnPreviousValue: true
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/v1/auth/**
        - id: account-service
          uri: lb://account-service
          predicates:
            - Path=/api/v1/account/**
        - id: content-service
          uri: lb://content-service
          predicates:
            - Path=/api/v1/content/**

auth-service:
  base-url: https://auth-service/api/v1/auth
  public-key-url: ${auth-service.base-url}/public-key